[project]
name = "need-nya"
version = "0.1.0"
description = ""
authors = [{ name = "Jeong Arm", email = "kjwonmail@gmail.com" }]
requires-python = "~=3.9"
dependencies = [
    "requests>=2.20.0",
    "Mastodon.py>=1.3.1",
    "lxml",
]
